# Generated by Django 5.1.5 on 2025-02-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('name_dri1', models.CharField(max_length=255)),
                ('name_dri2', models.CharField(max_length=255)),
                ('license_plate', models.IntegerField()),
                ('insurance', models.CharField(max_length=255)),
            ],
        ),
    ]
