# Generated by Django 5.1.4 on 2025-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtp',
            name='license_plate',
        ),
        migrations.AddField(
            model_name='dtp',
            name='license_plate1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dtp',
            name='license_plate2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
