# Generated by Django 5.1.4 on 2025-02-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_', '0002_remove_dtp_license_plate_dtp_license_plate1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dtp_drawings/'),
        ),
    ]
